### ISSUE TITLE
UX: js conflict with language select menu

### ISSUE THREAD

**Issue by Amgine0** [Piwigo/piwigo-openstreetmap#152]
The osm notification messages overlays the language select drop-down, even when minimized, when map is placed at category description.

![screencap language select with osm script](https://user-images.githubusercontent.com/1359795/33566320-79f0cd66-d917-11e7-8072-d190d7586035.jpeg)

**Comment by HWFord** [comment]
Issue with overlay and Modus menu also
https://github.com/Piwigo/piwigo-modus/issues/41
