### ISSUE TITLE
Pictures without GPS-information => PHP-8.0-warning

### ISSUE THREAD

**Issue by 1e-9** [Piwigo/piwigo-openstreetmap#229]
Pictures without GPS-information produce the following output when PHP 8.0 is activted:

Warning: Undefined array key "OSMJS" in /mnt/web115/a1/12/5421712/htdocs/piwigo/_data/templates_c/ljbwkp_bvtu6z^fd619a386ec1e7d13faef95df7bba10d138ce7b7_0.file.picture.tpl.php on line 327 Warning: Attempt to read property "value" on null in /mnt/web115/a1/12/5421712/htdocs/piwigo/_data/templates_c/ljbwkp_bvtu6z^fd619a386ec1e7d13faef95df7bba10d138ce7b7_0.file.picture.tpl.php on line 327

The named file contains this code from line 326:

if ($_smarty_tpl->tpl_vars['display_info']->value['rating_score'] && (isset($_smarty_tpl->tpl_vars['rate_summary']->value))) {
if ($_smarty_tpl->tpl_vars['OSMJS']->value) {?><div id="map-info" class="imageInfo"><dt <?php echo $_smarty_tpl->tpl_vars['OSMNAMECSS']->value;?>
><?php echo $_smarty_tpl->tpl_vars['OSMNAME']->value;?>
</dt><dd><div id="map"></div><?php echo '<script'; ?>
 type="text/javascript"><?php echo $_smarty_tpl->tpl_vars['OSMJS']->value;
echo '</script'; ?>
><div id="osm_attrib" style="visibility: hidden; display: none;"><ul><li><?php echo l10n("PLUGIN_BY");?>
</li><li><a href="http://leafletjs.com/" target="_blank">Leaflet</a></li><li>&copy; <?php echo l10n("OSM_CONTRIBUTORS");?>
</li></ul></div><?php if ($_smarty_tpl->tpl_vars['SHOWOSM']->value) {?><a href="<?php echo $_smarty_tpl->tpl_vars['OSMLINK']->value;?>
" target="_blank"><?php echo l10n("VIEW_OSM");?>
</a><?php }?></dd></div><?php }?><div id="Average" class="imageInfo"><dt><?php echo l10n('Rating score');?>
</dt><dd><?php if ($_smarty_tpl->tpl_vars['rate_summary']->value['count']) {?><span id="ratingScore"><?php echo $_smarty_tpl->tpl_vars['rate_summary']->value['score'];?>
</span> <span id="ratingCount">(<?php echo l10n_dec('%d rate','%d rates',$_smarty_tpl->tpl_vars['rate_summary']->value['count']);?>
)</span><?php } else { ?><span id="ratingScore"><?php echo l10n('no rate');?>
</span> <span id="ratingCount"></span><?php }?></dd></div><?php }

**Comment by 1e-9** [comment]
The code snippet is displayed incorrectly. 
Next try:
![2023-01-21 21_53_54-piwigo](https://user-images.githubusercontent.com/50927022/213886779-e90ef689-414a-4f2e-868c-47716866a90b.png)

**Comment by IngeWolters** [comment]
I got the same bug in the information/details tab.  I found it annoying so I started searching for the bug: 

In the file picture.inc.php, line 63, it says 

{if $OSMJS}

If you replace it with 

{if isset($OSMJS)}

the error will go away and you'll not see a map if there is no data available, instead of the error.  You can change it yourself (purge your  compiled templates if you do).  I have not searched for any other ifs, that might give the same problem, as I only use the map on the information/details tab...

**Comment by 4ndreasH** [comment]
same here: Piwigo 13.8.0, PHP 8.1.21
