### ISSUE TITLE
No access to Piwigo with 14.b

### ISSUE THREAD

**Issue by eTaurus** [Piwigo/piwigo-openstreetmap#246]
Environment:
Piwigo 14.2.0 (Docker container linuxserver.io)
Raspberry Pi arm64
PHP: 8.3.3
MySQL: 11.2.2-MariaDB-1:11.2.2+maria~ubu2204
Last working version of piwigo-openstreetmap: 13.c

Installing 14.b throws an error without description in the GUI. The extension is then listed as updated but deactivated. Activating the extension lead to the following error and no access to Piwigo.
```
Warning: file_put_contents(./osmmap.php): Failed to open stream: Permission denied in /config/www/plugins/piwigo-openstreetmap/maintain.class.php on line 162

Warning: Undefined variable $_error_reporting in /config/www/plugins/piwigo-openstreetmap/maintain.class.php on line 163

Warning: Undefined variable $PHPWG_ROOT_PATH in /config/www/plugins/piwigo-openstreetmap/maintain.class.php on line 164

Fatal error: Uncaught --> Smarty: unable to write file osmmap.php <-- thrown in /config/www/plugins/piwigo-openstreetmap/maintain.class.php on line 164
```

**Comment by Phil353556** [comment]
Hi, My 2cts when I read "Permission denied " what about the rights on directories and files?

**Comment by eTaurus** [comment]
> Hi, My 2cts when I read "Permission denied " what about the rights on directories and files?

They are the same as every other folder in the plugin directory. Version 13.c is working without any problems.

**Comment by martins250** [comment]
Updating previous comment: The update to version 14.a allowed Piwigo to function, but not this plugin. I reverted to 13.c to get the plugin working properlyas well.

**Comment by Stamgastje** [comment]
Same thing here: 14.b breaks Piwigo and 14.a die not function. I also had to switch back to 13.c.

Environment:
Piwigo 14.2.0
Operating system: Linux (Debian testing)
PHP: 8.2.12
MySQL: mariadb  Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
Graphics Library: ImageMagick 6.9.12-98 Q16 x86_64 18038

**Comment by raupie** [comment]
I noticed the openstreetmap wasn't appearing after the 14.3.0 update a few days ago. So I re-enabled the plugin and was presented with this same Smarty error. 

> Fatal error: Uncaught --> Smarty: unable to write file osmmap.php <-- thrown in /config/www/plugins/piwigo-openstreetmap/maintain.class.php on line 164

Which I have seen before and I resolved by manually creating the `/app/www/public/osmmap.php` by hand with a copy & paste of what maintain.class.php was trying to do but that no longer works.

Environment:
Piwigo 14.3.0
Environment:[ LinuxServer.io Docker-Piwigo](https://docs.linuxserver.io/images/docker-piwigo/) 

Indeed sounds related to folder/file permissions. Where's it trying to write to?

```
define('PHPWG_ROOT_PATH','./');
```

**Comment by Stamgastje** [comment]
This issue seems to be resolved in version 14.c, which was released on March 29. I just installed it and can now use the plugin without getting the error.

**Comment by martins250** [comment]
Now on Piwigo 14.3.0. Tried 14.c but got the Smarty errors in the post above by **raupie** https://github.com/Piwigo/piwigo-openstreetmap/issues/246#issuecomment-1986853476

Don't realy want to mess around with file permissions when everything else (and all the other plugins) are working nicely, so it's back to 13.c

**Comment by eTaurus** [comment]
Closed because they problem disappeared with version 14.d
Thank you!
