### ISSUE TITLE
Question about file osmmap.php which is written to PHPWG_ROOT_PATH

### ISSUE THREAD

**Issue by zero0cool0** [Piwigo/piwigo-openstreetmap#253]
I understand `maintain.class.php` is writing a file named `osmmap.php` into the root of the piwigo installation during the plugin installation process.

I'm curious to understand why it has to go into the piwigo root folder as this breaks the piwigo-upgrade process on my docker-based piwigo installation due to the official docker image default permission settings.

Wouldn't `$conf['data-location']` be a better home for this file?

**Comment by tfagart** [comment]
I've got the same issue than you. Do you have a workaround for now ?

**Comment by zero0cool0** [comment]
@tfagart  I've created PR #254 and hope it will be accepted. It stores the osmmap.php file in another folder. For now, I'm installing the modified plugin manually, but that is clearly not a long term solution.

**Comment by HWFord** [comment]
pr merged on 11/06/2024
