### ISSUE TITLE
Untranslated language strings in OSM plugin administration

### ISSUE THREAD

**Issue by MaraKat** [Piwigo/piwigo-openstreetmap#256]
Below is what is displayed when the language is set to French. I haven't checked other not-English languages. It's a mix of French and English. Osm plugin version : 14c.

>    137 geotagged items in your gallery
> 
> Display map on picture page
> Configuration if the active theme has a right pannel
> Configuration if the active theme has a left pannel
> Display map on category page
> This will display a map where the category description is
> 
>     Ajoute une carte dans la catégorie "Description" : Oui Non
>     Affiche une carte mondiale de l'album "description", affichera toutes les images dans l'album.
>     Show the map on all pages of the category : Oui Non
>     This will show a map on all pages of a category, not just in the category's description
>     Montrer la carte à :
> 
> 
> Affichera la carte à l'indice spécifié
> Hauteur de la carte :
> en pixel
> Largeur de la carte :
> en pixel ou automatique
> Sélectionnez un fichier GPX à afficher sur toutes les cartes de description des catégorie
> 
> Other places the map is displayed

**Comment by xbgmsharp** [comment]
Hello,
Feel free to update the translation. I will merge your update.

**Comment by xbgmsharp** [comment]
for add translation is better to register platform https://piwigo.org/translate/

**Comment by MaraKat** [comment]
There is a thread about it on the French forum. Someone already proposed new code and language strings, but I am not at ease with Github : https://fr.piwigo.org/forum/viewtopic.php?id=30470
