### ISSUE TITLE
Check if a geojson file exists

### ISSUE THREAD

**Issue by joubu** [Piwigo/piwigo-openstreetmap#89]
The current code use the omnivore plugin to display gpx data. It works great but generate an ajax request to the server for each gpx files.
Once the gpx data are retrieved, the parse.gpx (or whatever) function will generate a geojson structure to display the polygon.
If you have a lot of gpx files, this method could be a  high time-consuming process.

**Comment by xbgmsharp** [comment]
Thanks for the commit. It does require a lot of third party tool.
NodeJS and GPSBabel, A lot of user use Windows, it ill be difficult. We need a more straight forward and easy approach.

**Comment by xbgmsharp** [comment]
We could convert the GPX file directly to GeoJSON on upload. It would avoid the user to run the NodeJS app. 
If the use still have issue, we could provide an alternative to optimize/reduce the data via GPSBabel.

**Comment by xbgmsharp** [comment]
What about:
- User will submit the file, as usual.
- In the form processing PHP via trigger, I use cURL to execute a POST transmission to another NodeJS application, eg: https://github.com/xbgmsharp/nodejs-osmtag
- The remote script would do a GPX to GeoJSON and return the GeoJSON. Both content would be save in PWG.
